#pragma once

// These are often included headers that won't change much
// Included from API.h (dependent project pch) and Pcheader.h (tpublic pch)

#include "AuctionDuration.h"
#include "ComponentBase.h"
#include "EntityInstance.h"
#include "EntityState.h"
#include "DataErrorHandling.h"
#include "DataType.h"
#include "DialogueScript.h"
#include "Hash.h"
#include "Helpers.h"
#include "IReader.h"
#include "ItemInstance.h"
#include "ItemInstanceData.h"
#include "ItemInstanceReference.h"
#include "IWriter.h"
#include "LootRule.h"
#include "Manifest.h"
#include "MapData.h"
#include "MinionCommand.h"
#include "PerfTimer.h"
#include "Persistence.h"
#include "PersistentIdTable.h"
#include "PlayerTag.h"
#include "PlayerWorld.h"
#include "RangeBasedSet.h"
#include "Rarity.h"
#include "SourceContext.h"
#include "UIntRange.h"
#include "UniformDistribution.h"
#include "UTF8.h"
#include "Vec2.h"
#include "VectorIO.h"
#include "WordList.h"
