#pragma once

#include "DataType.h"
#include "IReader.h"
#include "ItemType.h"
#include "IWriter.h"
#include "SourceNode.h"

namespace tpublic
{

	class Requirement
	{
	public:
		enum Target : uint8_t
		{
			INVALID_TARGET,

			TARGET_TARGET,
			TARGET_SELF
		};

		enum Type : uint8_t
		{
			INVALID_TYPE,

			TYPE_MUST_HAVE_AURA,
			TYPE_MUST_NOT_HAVE_AURA,
			TYPE_MUST_HAVE_COMPLETED_QUEST,
			TYPE_MUST_NOT_HAVE_COMPLETED_QUEST,
			TYPE_MUST_HAVE_ACTIVE_QUEST,
			TYPE_MUST_NOT_HAVE_ACTIVE_QUEST,
			TYPE_MUST_HAVE_TAG,
			TYPE_MUST_BE_TYPE,
			TYPE_MUST_BE_IN_STATE,
			TYPE_MUST_NOT_BE_IN_STATE,
			TYPE_MUST_BE_HOSTILE,
			TYPE_MUST_BE_GROUP_MEMBER,
			TYPE_MUST_HAVE_ITEM_EQUIPPED,
			TYPE_MUST_HAVE_ITEM,
			TYPE_MUST_BE_FACTION,
			TYPE_MUST_HAVE_DISCOVERED_ZONE,
			TYPE_MUST_NOT_HAVE_PROFESSION_ABILITY,
			TYPE_MUST_NOT_HAVE_ITEM_EQUIPPED,
			TYPE_MUST_HAVE_LESS_HEALTH_THAN,
			TYPE_MUST_HAVE_NEGATIVE_REPUTATION,
			TYPE_MUST_HAVE_AURA_GROUP,
			TYPE_MUST_BE_CREATURE_TYPE,
			TYPE_MUST_HAVE_ZERO_HEALTH,
			TYPE_MUST_HAVE_ITEM_TYPE_EQUIPPED,
			TYPE_MUST_HAVE_EQUIPPED_ITEM_TYPE_FLAGS,
			TYPE_MUST_BE_AT_LEAST_LEVEL,
			TYPE_MUST_BE_DISCIPLE,
			TYPE_MUST_HAVE_MORE_RAGE_THAN,
			TYPE_MUST_NOT_BE_READY_TO_TURN_IN_QUEST,
			TYPE_MUST_NOT_BE_TYPE,
			TYPE_MUST_NOT_HAVE_ITEM,
			TYPE_MUST_HAVE_REPUTATION_LEVEL,
			TYPE_MUST_NOT_HAVE_EQUIPPED_ITEM_TYPE_FLAGS,
			TYPE_MUST_NOT_BE_CREATURE_TYPE,
			TYPE_MUST_KNOW_RIDING,
			TYPE_MUST_NOT_KNOW_RIDING,
			TYPE_MUST_NOT_BE_DISCIPLE,
			TYPE_MUST_NOT_HAVE_DISCOVERED_ZONE,
			TYPE_MUST_NOT_HAVE_STARTED_SURVIVAL,
			TYPE_MUST_HAVE_STARTED_SURVIVAL,
			TYPE_MUST_NOT_BE_ON_MAP,
			TYPE_MUST_BE_ON_MAP,
			TYPE_MUST_HAVE_FISHING_ROD_EQUIPPED,
			TYPE_MUST_NOT_HAVE_SOURCE_AURA,
			TYPE_MUST_HAVE_AURA_FLAGS,
			TYPE_MUST_NOT_BE_ELITE,
			TYPE_MUST_BE_ELITE,
			TYPE_MUST_BE_LOWER_THAN_LEVEL,
			TYPE_MUST_BE_NPC_WITH_HEAD_ANCHOR,
			TYPE_MUST_BE_HEROIC,
			TYPE_MUST_NOT_BE_HEROIC,
			TYPE_MUST_NOT_BE_FRIENDLY_FACTION
		};

		static DataType::Id		GetDataType(
									Type					aType);
		static uint32_t			TypeAndSourceToId(
									Type					aType,
									const SourceNode*		aSource);

								Requirement();
								Requirement(
									const SourceNode*		aSource);
		
		void					FromSource(
									const SourceNode*		aSource);
		void					ToStream(
									IWriter*				aWriter) const;
		bool					FromStream(
									IReader*				aReader);

		// Public data
		Target								m_target = INVALID_TARGET;
		Type								m_type = INVALID_TYPE;
		uint32_t							m_id = 0;
		uint32_t							m_value = 0;
	};

}